@echo off
echo [+] Initializing Git Repository...
git init
echo [+] Configuring Remote Origin...
git remote remove origin >nul 2>&1
git remote add origin https://github.com/Bhushan-narware/cyber-portfolio.git
echo [+] Staging files...
git add -A
echo [+] Committing changes...
git commit -m "Initialize portfolio with anti-gravity cybersecurity HUD, Threat Map, Academic records, and interactive simulators"
echo [+] Renaming branch to main...
git branch -M main
echo [+] Pushing to GitHub (Requires Authentication)...
git push -u origin main
echo [+] Process complete.
